# Generated by Django 3.1.2 on 2022-01-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thjcrm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('activa', 'activa'), ('inactiva', 'inactiva')], max_length=35),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('property', 'schedule')},
        ),
    ]
