# Generated by Django 3.1.2 on 2022-01-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thjcrm', '0002_auto_20220106_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('active', 'activo'), ('done', 'realizada'), ('cancel', 'cancelada')], max_length=35),
        ),
        migrations.RemoveField(
            model_name='survey',
            name='activity',
        ),
        migrations.AddField(
            model_name='survey',
            name='activity',
            field=models.ManyToManyField(to='thjcrm.Activity'),
        ),
    ]
